name: Terraform Apply

on: [push]

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Terraform
      env:
        TERRAFORM_VERSION: "0.12.28"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        SSH_FINGERPRINT: ${{ secrets.SSH_FINGERPRINT }}
        SERVER_COUNT: ${{ secrets.SERVER_COUNT }}
      run: terraform init -input=false

    - name: Terraform validation
      run: terraform validate

    - name: Terraform apply
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        SSH_FINGERPRINT: ${{ secrets.SSH_FINGERPRINT }}
        SERVER_COUNT: ${{ secrets.SERVER_COUNT }}
      run: terraform apply -var "ssh_fingerprint=${SSH_FINGERPRINT}" -var "server_count=${SERVER_COUNT}" -auto-approve -input=false
